---
title: "Lecture 1005"
author: "ssheng6"
date: "10/5/2021"
output: html_document
---

```{r }
library(dplyr)
library(nycflights13)
library(lubridate)
library(ggplot2)
library(tidyr)
library(tidyverse)

weather

weather2 <- 
  weather %>%
  mutate(date = make_date(year,month,day))%>%
  group_by(date,origin)%>%
  summarise(min_vis = min(visib, na.rm = T), mean_vis = mean(visib,na.rm = T))



flights %>%
  mutate(date = make_date(year,month,day)) %>%
  group_by(date, origin) %>%
  summarise(proportion_cancelled = mean(is.na(dep_time)))%>%
  left_join(weather2) %>% 
  ggplot(aes(x = min_vis,y = proportion_cancelled))+
  geom_point()+
  geom_smooth(se = F, method = "lm")+
  facet_wrap(~origin)


#ggplot()+facet_wrap(~origin)+geom_lines(aes(x=flights$time_hour, y=))

```

```{r}
library(nycflights13)
mpg
#library(ggplot2)
library(dplyr)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy) )+
  facet_wrap(~class, nrow = 2)

planes

flights%>%left_join(planes, by = "tailnum")
```