---
title: "HW3"
author: "ssheng6"
date: "9/28/2021"
output: html_document
---

```{r}
# install.packages("nycflights13")
require(nycflights13)
require(ggplot2)
require(dplyr)

flights

# Q1 (1) How many flights have a missing dep_time? 
filter(flights,is.na(dep_time)) 
#8255 flights has a missing dep_time 

# Q1 (2)What other variables are missing? What might these rows represent?
# dep_time, dep_delay, arr_time, arr_delay,air_time is missing. 
# when flight cancelled. dep_time, dep_delay,arr_time,arr delay will be all missing
# when arr_delay is na. arr_time has value, flight may be rerouted to another airport.
# when dep_time and dep_delay has value, and both arr_time and arr_delay is na, flight may be missing. or data has missing information. 
# in no situation, dep_delay has value, while dep_time has no value. 

filter(flights,is.na(dep_delay),!is.na(dep_time))
filter(flights,is.na(arr_time),!is.na(arr_delay))
filter(flights,is.na(arr_delay))
filter(flights,is.na(arr_time),!is.na(arr_delay))
```

```{r}

# Q2 Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.

library(nycflights13)
require(ggplot2)
require(dplyr)

flightmin <- mutate(flights,
                    dep_min=(flights$dep_time%/%100*60)+flights$dep_time%%100,
                    sched_dep_min=(sched_dep_time%/%100*60)+flights$sched_dep_time%%100)
print(flightmin)


```

```{r}
# Q3 Look at the number of canceled flights per day. Is there a pattern? Is the proportion of canceled flights related to the average delay? Use multiple dyplr operations, all on one line, concluding with ggplot(aes(x= ,y=)) + geom_point()
library(nycflights13)
require(dplyr)
library(lubridate) 
library(ggplot2)
library(tidyverse)

flight_nc <- flights %>% 
  mutate(cancelled = (is.na(flights$dep_delay)|is.na(flights$arr_delay)))%>%
  mutate(day=yday(flights$time_hour))%>%
  group_by(year, month, day) %>%
  summarise(cancelled = sum(cancelled)) 
  #%>%ungroup
  #%>%
  #mutate(day=(1:nrow(flight_nc)))
  
flight_nc
#cancel frequency by any day of a year
ggplot(flight_nc, aes(day,cancelled)) +  geom_line()+ggtitle("total delay for each day in a year")+theme(plot.title = element_text(hjust = 0.5))
```

```{r}
library(nycflights13)
flight2<- flights %>%
  summarise(avg_delay1 = mean(arr_delay))
    
#cancel frequency per weekday
flights %>% mutate(dayWeek = wday(time_hour)) %>% 
  group_by(dayWeek)%>% summarize(cancelled = sum((is.na(flights$dep_delay)|is.na(flights$arr_delay)))) %>% 
  plot
```



